#######
#
# bootstrap5-template
# basic bootstrap 5 template for Jekyll with GitHub Pages
# https://github.com/thecdil/bootstrap5-template
#
#######

#######
# SITE SETTINGS
#
title: Image Annotate
description: "a basic template to present annotated images"
year: 2026
author: evan will 
#organization-name: 
# add search box to navbar, true/false
search: false
# add representative image for social media sharing
# use a relative link to image file in project or full url
#featured-image:
#featured-image-alt:

##########
# Annotation style defaults
#
annotation-fill: "#cdcdcd" # a color value
annotation-fillOpacity: 0.1 # number 0 - 1
annotation-stroke: "#f1b300" # a color value
annotation-strokeOpacity: 1 # number 0 - 1
annotation-strokeWidth: 3 # a number

##########
# URL VARIABLES [optional!]
#
# Optional if using GitHub Pages! If building manually, these must be set correctly.
#
# use url for the domain, e.g. https://thecdil.github.io
# on gh-pages follow the pattern: https://username.github.io
url:
# use baseurl to add subsection of the domain, e.g. /timelinejs-template
# on gh-pages this is a / followed by the name of the repository
# baseurl is your github repository's name prefixed with a /
baseurl:
# location of code, the full url to your github repository
source-code: https://github.com/evanwill/image-annotate-template

##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter,
# all files in the "pages" folder will be output at root of site
defaults:
  - scope:
      path: "pages"
    values:
      layout: page
      permalink: /:basename:output_ext

# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
